apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: geot94xef-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: geot94xef-nodejs 
  name: geot94xef-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: geot94xef-nodejs 
